#!/bin/bash

sudo apt-get install -y nginx
echo 'Install Nginx'

# copy file over to there ...
sudo cp nginx.conf /etc/nginx/
echo 'Nginx config file setup'

# reload service
sudo systemctl restart nginx
echo 'Nginx restarting'

# daemon-reload
sudo systemctl daemon-reload
echo 'Daemon reloading'
