#!/bin/bash

sudo yum update
sudo amazon-linux-extras install -y epel nginx1
sudo yum install epel-release nginx
echo 'Install Nginx'

# copy file over to there ...
sudo cp nginx.conf /etc/nginx/

echo 'Nginx config file setup'

# reload service
sudo systemctl restart nginx
echo 'Nginx restarting'

# daemon-reload
sudo systemctl daemon-reload
echo 'Daemon reloading'

# if it errors hard, try enabling this
# sudo systemctl reenable nginx

# daemon-reload
sudo systemctl daemon-reload

# reload service
sudo systemctl restart nginx

