#!/bin/bash

sudo systemctl stop nginx

sudo systemctl disable nginx
echo '*' *service stopped*

sudo apt-get purge -y nginx nginx-common
sudo apt-get autoremove -y nginx

sudo rm -r /etc/nginx

echo '*' *service removed*

# sudo userdel -r jenkins

echo *user profiles deleted*

sudo systemctl daemon-reload
sudo systemctl reset-failed

echo '*' *service shut down*
